// <auto-generated />
using System;
using ClinicalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ClinicalAPI.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    [Migration("20260713095451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicalAPI.Models.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DIAGNOSIS");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DOCTOR_NAME");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOTES");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PATIENT_ID");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PATIENT_NAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("STATUS");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("SYMPTOMS");

                    b.Property<string>("Treatment")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TREATMENT");

                    b.Property<DateTime>("VisitDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("VISIT_DATE")
                        .HasDefaultValueSql("SYSDATE");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_MEDICAL_RECORDS_PATIENT_ID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MEDICAL_RECORDS_STATUS");

                    b.ToTable("MEDICAL_RECORDS", (string)null);
                });

            modelBuilder.Entity("ClinicalAPI.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CATEGORY");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("COST_PRICE");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("GENERIC_NAME");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MANUFACTURER");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("SELL_PRICE");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("STOCK_QUANTITY");

                    b.Property<string>("Strength")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STRENGTH");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TRADE_NAME");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT")
                        .HasDefaultValueSql("SYSDATE");

                    b.HasKey("Id");

                    b.HasIndex("GenericName")
                        .HasDatabaseName("IX_MEDICINES_GENERIC_NAME");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MEDICINES_IS_ACTIVE");

                    b.ToTable("MEDICINES", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
